title: "Joel TERMONDJIAN"
description: "Data Analyst / Data Engineer | Ancien professionnel de la banque (20 ans) reconverti en data. J’utilise la data et l’automatisation pour transformer des données brutes en outils d’aide à la décision."
theme: jekyll-theme-minimal
logo: "assets/Photo.jpg"

plugins:
  - jekyll-seo-tag

SEO_email: "joel.termondjian@hotmail.com"
show_downloads: true                    
